UPDATE rel1 SET c1 = DEFAULT, c2 = DEFAULT
UPDATE rel2 SET c1 = DEFAULT, c2 = DEFAULT
UPDATE rel1 SET c1 = now(), c2 = CURRENT_DATE
UPDATE rel1 SET (c3, c4) = (CURRENT_TIMESTAMP, CURRENT_TIME)
UPDATE rel1 SET c1 = LOCALTIMESTAMP, c2 = LOCALTIME
PREPARE q(int) AS UPDATE rel1 SET c1 = $1, c2 = CURRENT_DATE
