VACUUM;
VACUUM FULL;
VACUUM FULL FREEZE;
VACUUM FULL FREEZE VERBOSE;
VACUUM FULL FREEZE VERBOSE ANALYZE;
VACUUM FULL t;
ANALYZE
ANALYZE VERBOSE
ANALYZE VERBOSE x
ANALYZE VERBOSE x(a,b,c);
EXPLAIN SELECT * FROM t;
EXPLAIN ANALYZE SELECT * FROM t;
EXPLAIN ANALYZE VERBOSE SELECT * FROM t;
REINDEX INDEX x
REINDEX INDEX x force
REINDEX TABLE x
REINDEX TABLE x force
REINDEX DATABASE x
REINDEX DATABASE x force
REINDEX SYSTEM x
REINDEX SYSTEM x force
LISTEN x
NOTIFY x
DISCARD ALL
DISCARD TEMP
DISCARD TEMPORARY
DISCARD PLANS
DISCARD xxx
