SELECT INTERVAL(0) '1.23' SECOND;
SELECT INTERVAL '1 year' HOUR TO SECOND(2)
SELECT char 'ABC';
SELECT "char" 'ABC';
SELECT avg(c1) OVER (PARTITION BY depname RANGE UNBOUNDED PRECEDING) FROM r1;
SELECT avg(c1) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM r1;
SELECT sum(c1) OVER w1 FROM r1 WINDOW w1 AS (PARTITION BY c2 ORDER BY c3), w2 AS (w1 PARTITION BY c4);
WITH w1(n) AS (SELECT 1), w2(n) AS (SELECT 2) SELECT sum(n) FROM r1;
WITH RECURSIVE t(n) AS (VALUES (1) UNION ALL SELECT n+1 FROM t WHERE n  < 100) SELECT sum(n) FROM t;
ALTER AGGREGATE FOO(int) OWNER TO BAR;
ALTER CONVERSION FOO OWNER TO BAR;
ALTER DATABASE FOO OWNER TO BAR;
ALTER DOMAIN FOO OWNER TO BAR;
ALTER FUNCTION FOO() OWNER TO BAR;
ALTER LANGUAGE FOO OWNER TO BAR;
ALTER OPERATOR + (int, int) OWNER TO BAR;
ALTER OPERATOR CLASS FOO USING BAZ OWNER TO BAR;
ALTER OPERATOR FAMILY FOO USING BAZ OWNER TO BAR;
ALTER TYPE FOO OWNER TO BAR;
ALTER TABLESPACE FOO OWNER TO BAR;
ALTER TEXT SEARCH DICTIONARY FOO OWNER TO BAR;
ALTER TEXT SEARCH CONFIGURATION FOO OWNER TO BAR;
ALTER FOREIGN DATA WRAPPER FOO OWNER TO BAR;
ALTER SERVER FOO OWNER TO BAR;
ALTER SCHEMA FOO OWNER TO BAR;
LISTEN x
NOTIFY x
UNLISTEN x
UNLISTEN *
CREATE TRIGGER t1 BEFORE INSERT OR UPDATE OR DELETE OR TRUNCATE ON r1 EXECUTE PROCEDURE p1();
GRANT ALL ON r1 TO PUBLIC;
GRANT ALL ON SEQUENCE r1 TO PUBLIC;
GRANT ALL ON FUNCTION r1() TO PUBLIC;
GRANT ALL ON DATABASE r1 TO PUBLIC;
GRANT ALL ON LANGUAGE r1 TO PUBLIC;
GRANT ALL ON SCHEMA r1 TO PUBLIC;
GRANT ALL ON TABLESPACE r1 TO PUBLIC;
